version: '3.8'
services:
  app:
    build: .
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
